// Generated by ego.
// DO NOT EDIT

package exporter
import (
"fmt"
"html"
"io"
"github.com/pborman/uuid"
"time"
"bytes"
"github.com/projectcypress/cdatools/models"
)
var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
//line templates/_addresses.ego:1
 func AddressesTmpl(w io.Writer, address *models.Address) error  {
//line templates/_addresses.ego:2
_, _ = io.WriteString(w, "\n<addr use=\"address.Use\">\n    ")
//line templates/_addresses.ego:3
 for _, street := range address.Street { 
//line templates/_addresses.ego:3
_, _ = io.WriteString(w, "<streetAddressLine>")
//line templates/_addresses.ego:3
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  street )))
//line templates/_addresses.ego:3
_, _ = io.WriteString(w, "</streetAddressLine>")
//line templates/_addresses.ego:3
 } 
//line templates/_addresses.ego:4
_, _ = io.WriteString(w, "\n    <city>")
//line templates/_addresses.ego:4
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.City )))
//line templates/_addresses.ego:4
_, _ = io.WriteString(w, "</city>\n    <state>")
//line templates/_addresses.ego:5
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.State )))
//line templates/_addresses.ego:5
_, _ = io.WriteString(w, "</state>\n    <postalCode>")
//line templates/_addresses.ego:6
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.Zip )))
//line templates/_addresses.ego:6
_, _ = io.WriteString(w, "</postalCode>\n    <country>")
//line templates/_addresses.ego:7
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.Country )))
//line templates/_addresses.ego:7
_, _ = io.WriteString(w, "</country>\n</addr>\n")
return nil
}
//line templates/_author.ego:1
 func AuthorTmpl(w io.Writer, author *models.Person) error  {
//line templates/_author.ego:2
_, _ = io.WriteString(w, "\n\n<!-- SHALL have 1..* author. MAY be device or person.\n    The author of the CDA document in this example is a device at a data submission vendor/registry. -->\n<author>\n\n</author>\n")
return nil
}
//line templates/_id.ego:1
 func IdTmpl(w io.Writer, identifier *models.ID) error  {
//line templates/_id.ego:2
_, _ = io.WriteString(w, "\n\n")
//line templates/_id.ego:3
 if (identifier.Root != "") { 
//line templates/_id.ego:4
_, _ = io.WriteString(w, "\n  <id root=\"")
//line templates/_id.ego:4
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  identifier.Root )))
//line templates/_id.ego:4
_, _ = io.WriteString(w, "\"  extension=\"")
//line templates/_id.ego:4
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  identifier.Extension )))
//line templates/_id.ego:4
_, _ = io.WriteString(w, "\" />\n")
//line templates/_id.ego:5
 } else { 
//line templates/_id.ego:6
_, _ = io.WriteString(w, "\n  <id extension=\"")
//line templates/_id.ego:6
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  identifier.Extension )))
//line templates/_id.ego:6
_, _ = io.WriteString(w, "\" />\n")
//line templates/_id.ego:7
 } 
//line templates/_id.ego:8
_, _ = io.WriteString(w, "\n")
return nil
}
//line templates/_record_target.ego:1
 func RecordTargetTmpl(w io.Writer, patient *models.Record) error  {
//line templates/_record_target.ego:2
_, _ = io.WriteString(w, "\n\n<recordTarget>\n  <patientRole>\n    ")
//line templates/_record_target.ego:5
 if (patient.MedicalRecordNumber != "" && patient.MedicalRecordAssigner != "") { 
//line templates/_record_target.ego:6
_, _ = io.WriteString(w, "\n      ")
//line templates/_record_target.ego:6
 mrn := models.ID{Root: patient.MedicalRecordNumber, Extension: patient.MedicalRecordAssigner} 
//line templates/_record_target.ego:7
_, _ = io.WriteString(w, "\n      ")
//line templates/_record_target.ego:7
 var buffer bytes.Buffer 
//line templates/_record_target.ego:7
_, _ = io.WriteString(w, " ")
//line templates/_record_target.ego:7
 IdTmpl(&buffer, &mrn) 
//line templates/_record_target.ego:7
_, _ = io.WriteString(w, " ")
//line templates/_record_target.ego:7
 io.WriteString(w, buffer.String()) 
//line templates/_record_target.ego:8
_, _ = io.WriteString(w, "\n    ")
//line templates/_record_target.ego:8
 } else { 
//line templates/_record_target.ego:9
_, _ = io.WriteString(w, "\n      <id extension=\"12345\" root=\"PlaceholderOrganization\" />\n    ")
//line templates/_record_target.ego:10
 } 
//line templates/_record_target.ego:11
_, _ = io.WriteString(w, "\n    <addr use=\"HP\">\n      ")
//line templates/_record_target.ego:12
 if (patient.Addresses != nil) { 
//line templates/_record_target.ego:13
_, _ = io.WriteString(w, "\n      ")
//line templates/_record_target.ego:13
 for _, address := range patient.Addresses { 
//line templates/_record_target.ego:14
_, _ = io.WriteString(w, "\n        ")
//line templates/_record_target.ego:14
 for _, street := range address.Street { 
//line templates/_record_target.ego:14
_, _ = io.WriteString(w, "<streetAddressLine>")
//line templates/_record_target.ego:14
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  street )))
//line templates/_record_target.ego:14
_, _ = io.WriteString(w, "</streetAddressLine>")
//line templates/_record_target.ego:14
 } 
//line templates/_record_target.ego:15
_, _ = io.WriteString(w, "\n        <city>")
//line templates/_record_target.ego:15
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.City )))
//line templates/_record_target.ego:15
_, _ = io.WriteString(w, "</city>\n        <state>")
//line templates/_record_target.ego:16
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.State )))
//line templates/_record_target.ego:16
_, _ = io.WriteString(w, "</state>\n        <postalCode>")
//line templates/_record_target.ego:17
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.Zip )))
//line templates/_record_target.ego:17
_, _ = io.WriteString(w, "</postalCode>\n        <country>")
//line templates/_record_target.ego:18
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  address.Country )))
//line templates/_record_target.ego:18
_, _ = io.WriteString(w, "</country>\n      ")
//line templates/_record_target.ego:19
 } 
//line templates/_record_target.ego:20
_, _ = io.WriteString(w, "\n      ")
//line templates/_record_target.ego:20
 } else { 
//line templates/_record_target.ego:21
_, _ = io.WriteString(w, "\n        <streetAddressLine>202 Burlington Rd.</streetAddressLine>\n        <city>Bedford</city>\n        <state>MA</state>\n        <postalCode>01730</postalCode>\n        <country>US</country>\n      ")
//line templates/_record_target.ego:26
 } 
//line templates/_record_target.ego:27
_, _ = io.WriteString(w, "\n    </addr>\n    <telecom use=\"WP\" value=\"tel:+1-781-271-3000\"/>\n    <patient>\n      <name>\n        <given>")
//line templates/_record_target.ego:31
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.First )))
//line templates/_record_target.ego:31
_, _ = io.WriteString(w, "</given>\n        <family>")
//line templates/_record_target.ego:32
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Last )))
//line templates/_record_target.ego:32
_, _ = io.WriteString(w, "</family>\n      </name>\n      <administrativeGenderCode code=\"")
//line templates/_record_target.ego:34
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Gender )))
//line templates/_record_target.ego:34
_, _ = io.WriteString(w, "\" codeSystem=\"2.16.840.1.113883.5.1\" codeSystemName=\"HL7 AdministrativeGender\"/>\n      <birthTime value=\"")
//line templates/_record_target.ego:35
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Birthdate )))
//line templates/_record_target.ego:35
_, _ = io.WriteString(w, "\"/>\n      ")
//line templates/_record_target.ego:36
 if (&patient.Race != nil) { 
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, "\n        <raceCode code=\"")
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Race.Code )))
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, "\" ")
//line templates/_record_target.ego:37
 if (patient.Race.Name != "") { 
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, "displayName=\"")
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Race.Name )))
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, "\"")
//line templates/_record_target.ego:37
 } 
//line templates/_record_target.ego:37
_, _ = io.WriteString(w, " codeSystemName=\"CDC Race and Ethnicity\" codeSystem=\"2.16.840.1.113883.6.238\"/>\n      ")
//line templates/_record_target.ego:38
 } 
//line templates/_record_target.ego:39
_, _ = io.WriteString(w, "\n      ")
//line templates/_record_target.ego:39
 if (&patient.Ethnicity != nil) { 
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, "\n        <ethnicGroupCode code=\"")
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Ethnicity.Code )))
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, "\" ")
//line templates/_record_target.ego:40
 if (patient.Ethnicity.Name != "") { 
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, "displayName=\"")
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  patient.Ethnicity.Name )))
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, "\"")
//line templates/_record_target.ego:40
 } 
//line templates/_record_target.ego:40
_, _ = io.WriteString(w, " codeSystemName=\"CDC Race and Ethnicity\" codeSystem=\"2.16.840.1.113883.6.238\"/>\n      ")
//line templates/_record_target.ego:41
 } 
//line templates/_record_target.ego:42
_, _ = io.WriteString(w, "\n      <!-- LANGUAGE SECTION GOES HERE -->\n\n    </patient>\n  </patientRole>\n</recordTarget>\n")
return nil
}
//line templates/cat1.ego:1
 func Cat1Tmpl(w io.Writer, patient *models.Record) error  {
//line templates/cat1.ego:2
_, _ = io.WriteString(w, "\n\n")
//line templates/cat1.ego:4
_, _ = io.WriteString(w, "\n")
//line templates/cat1.ego:5
_, _ = io.WriteString(w, "\n")
//line templates/cat1.ego:6
_, _ = io.WriteString(w, "\n")
//line templates/cat1.ego:7
_, _ = io.WriteString(w, "\n\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<ClinicalDocument xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n xmlns=\"urn:hl7-org:v3\"\n xmlns:voc=\"urn:hl7-org:v3/voc\"\n xmlns:sdtc=\"urn:hl7-org:sdtc\">\n  <!-- QRDA Header -->\n  <realmCode code=\"US\"/>\n  <typeId root=\"2.16.840.1.113883.1.3\" extension=\"POCD_HD000040\"/>\n  <!-- US Realm Header Template Id -->\n  <templateId root=\"2.16.840.1.113883.10.20.22.1.1\"/>\n  <!-- QRDA templateId -->\n  <templateId root=\"2.16.840.1.113883.10.20.24.1.1\" />\n  <!-- QDM-based QRDA templateId -->\n  <templateId root=\"2.16.840.1.113883.10.20.24.1.2\" />\n  <!-- This is the globally unique identifier for this QRDA document -->\n  <id root=\"")
//line templates/cat1.ego:23
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  uuid.NewRandom() )))
//line templates/cat1.ego:23
_, _ = io.WriteString(w, "\"/>\n  <!-- QRDA document type code -->\n  <code code=\"55182-0\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\" displayName=\"Quality Measure Report\"/>\n  <title>QRDA Incidence Report</title>\n  <!-- This is the document creation time -->\n  <effectiveTime value=\"")
//line templates/cat1.ego:28
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  time.Now().UTC().Unix() )))
//line templates/cat1.ego:28
_, _ = io.WriteString(w, "\"/>\n  <confidentialityCode code=\"N\" codeSystem=\"2.16.840.1.113883.5.25\"/>\n  <languageCode code=\"en\"/>\n  <!-- reported patient -->\n  ")
//line templates/cat1.ego:32
 var buffer bytes.Buffer 
//line templates/cat1.ego:32
_, _ = io.WriteString(w, " ")
//line templates/cat1.ego:32
 RecordTargetTmpl(&buffer, patient) 
//line templates/cat1.ego:32
_, _ = io.WriteString(w, " ")
//line templates/cat1.ego:32
 io.WriteString(w, buffer.String()) 
//line templates/cat1.ego:33
_, _ = io.WriteString(w, "\n\n\n</ClinicalDocument>\n")
return nil
}
