build:
	go-bindata -o templates.go -pkg exporter templates/*/*.xml

debug:
	go-bindata -o templates.go -pkg exporter --debug templates/*/*.xml

# fake out clean and install
clean:
install:

.PHONY: build
