sudo: true
language: go
go:
- 1.6
branches:
  only:
  - master
install:
- sudo apt-get -qq update
- sudo apt-get -y install libxml2-dev
- go get -u github.com/jteeuwen/go-bindata/...
- go get -t ./...
script: go test -v ./...
notifications:
  slack:
    secure: fE9UDcxXR2kXnZ7xOyHSz9G+jyWWO0dFAd8FYZM1v3336SOfFbwLsaX4LuJt9dT3iSt4yO+ZpRDmbDz1uCtm5qVp5ybjeo0JwXbIow3j7Zaf3lncSFAC8xujxkHE1mdg1W4NDM16/lHsZgPD0siFGLf3io+A8mGLXgsW+ox+5r5bJlHaAPc8vt6kFMQMCmNiSN7iDCz18nwTWeflO70MXWAB5hDca1AKvulEqCi3aAFgEsajtUMlAt7bR7gUik2IhTsPQZ1OxIlIWhU8H0QNooUunOPn6gJGJShlg3mSLxvXSP6Ce9o+xO42gw72/Rlvmiq1ACZw5yfRmh3H++f2Yomg958ozbr1ujZOgcHh4b9HwYAiwvqwHh54bLRj/dhR2T3zxi7+uc2vWCLcEyWGNPkUatP8NUItuBP91xhPKPdBuFNS6ufN3vdeENQWiQNg//IvRTiEUe4N8jyKLimXMT2NLCcnJuB8T5pMMDSm5bAXMvLbZ1/XmM0l/cEAnzBtmx1yXba0B4Nb80KMXC+WW1Sh6GdY6inWH+Lu4vFaYpwHMN6pDQyIKPyqrDr/LMNy4bVg//gHfgeoJkUVfI6bxz0bB7xjRSOaKist74Qlvzxp5DS23Bj6fwagOATMsQRKab0ZJrWMZqdipWtBLeWQ5QRK6+6rph+SnX/xWAEs5rk=
